// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protodata.proto

package dinoproto2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Animal struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	AnimalType           *string  `protobuf:"bytes,2,req,name=animal_type,json=animalType" json:"animal_type,omitempty"`
	Nickname             *string  `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Zone                 *int32   `protobuf:"varint,4,req,name=zone" json:"zone,omitempty"`
	Age                  *int32   `protobuf:"varint,5,opt,name=age" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Animal) Reset()         { *m = Animal{} }
func (m *Animal) String() string { return proto.CompactTextString(m) }
func (*Animal) ProtoMessage()    {}
func (*Animal) Descriptor() ([]byte, []int) {
	return fileDescriptor_protodata_699156f0047eed81, []int{0}
}
func (m *Animal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Animal.Unmarshal(m, b)
}
func (m *Animal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Animal.Marshal(b, m, deterministic)
}
func (dst *Animal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Animal.Merge(dst, src)
}
func (m *Animal) XXX_Size() int {
	return xxx_messageInfo_Animal.Size(m)
}
func (m *Animal) XXX_DiscardUnknown() {
	xxx_messageInfo_Animal.DiscardUnknown(m)
}

var xxx_messageInfo_Animal proto.InternalMessageInfo

func (m *Animal) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Animal) GetAnimalType() string {
	if m != nil && m.AnimalType != nil {
		return *m.AnimalType
	}
	return ""
}

func (m *Animal) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *Animal) GetZone() int32 {
	if m != nil && m.Zone != nil {
		return *m.Zone
	}
	return 0
}

func (m *Animal) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Animal)(nil), "dinoproto2.animal")
}

func init() { proto.RegisterFile("protodata.proto", fileDescriptor_protodata_699156f0047eed81) }

var fileDescriptor_protodata_699156f0047eed81 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcc, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x05, 0x60, 0x92, 0x36, 0x62, 0x4f, 0x50, 0xb9, 0x29, 0xb8, 0x18, 0x9c, 0x32, 0x39, 0xf8,
	0x53, 0x82, 0xbb, 0x1c, 0x26, 0xc8, 0xa1, 0xbd, 0x04, 0xc9, 0x52, 0xfd, 0xf3, 0x62, 0x0a, 0xdd,
	0xbe, 0xf7, 0x1e, 0x3c, 0xd8, 0x95, 0x77, 0xae, 0x39, 0x52, 0xa5, 0x73, 0x13, 0x42, 0x64, 0xc9,
	0x8d, 0x97, 0xd3, 0x17, 0x56, 0x24, 0x3c, 0xd2, 0x0b, 0xb7, 0xa0, 0x39, 0x5a, 0xe5, 0xb4, 0x37,
	0x41, 0x73, 0xc4, 0x23, 0x6c, 0xe6, 0xe5, 0x56, 0xa7, 0x92, 0xac, 0x76, 0xda, 0x0f, 0x01, 0xe6,
	0xea, 0x3a, 0x95, 0x84, 0x07, 0x58, 0x0b, 0xdf, 0x9f, 0x42, 0x63, 0xb2, 0x9d, 0x53, 0x7e, 0x08,
	0x4b, 0x46, 0x84, 0xfe, 0x93, 0x25, 0xd9, 0xbe, 0xdd, 0x35, 0xe3, 0x1e, 0x3a, 0x7a, 0x24, 0x6b,
	0x9c, 0xf2, 0x26, 0xfc, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x50, 0xb2, 0x1d, 0x9a, 0x00,
	0x00, 0x00,
}
